server:
  port: 8080
  servlet:
    context-path: /futscore

spring:
  application:
    name: futscore
  datasource:
    url: jdbc:mysql://localhost:3306/futebol
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
